Repository Code20Project/KMC-Server, pull requests merged in 2020-09, with the labels that each got.

#7 Add: Set config.js
  Server/config/config.js
  Server/config/config.json
  Server/models/index.js
Labels: DB

#9 Feat : Set basic node server
  Server/app.js
  Server/package-lock.json
  Server/package.json
Labels: C: 1h, Sprint2

#10 Feat: Create DB
  Server/config/config.js
  Server/migrations/202009021224-user.js
  Server/migrations/202009021225-boardtype.js
  Server/migrations/202009021226-board.js
  Server/migrations/202009021227-file.js
  Server/models/board.js
  Server/models/boardtype.js
  Server/models/file.js
  Server/models/user.js
  Server/package-lock.json
  Server/package.json
Labels: C: 1h, DB

#16 Feat : Set JWT
  Server/JWT/index.js
  Server/app.js
  Server/package-lock.json
  Server/package.json
Labels: Bare, C: 1h, DB, Sprint3

#18 Feat : Encrypt-userPassword
  Server/models/user.js
Labels: Bare, C: 1h, DB, Sprint3

#21 Feat : Create-userSignup
  Server/controllers/user/signup.js
  Server/models/index.js
  Server/models/user.js
  Server/package-lock.json
Labels: Bare, C:3h, DB, Sprint3

#22 Feat : Complete to create user Signin feature
  Server/controllers/user/signin.js
Labels: Bare, C: 1h, DB, Sprint3

#23 Feat : Create user Profile
  Server/controllers/user/profile.js
Labels: Bare, C:2h, DB, Sprint3

#24 Feat: eslint setting
  Server/.eslintrc.json
  Server/package-lock.json
  Server/package.json
Labels: C: 1h

#26 Add : Add eslint rules
  Server/.eslintrc.json
Labels: Bare, C: 1h, sprint4

#39 Feat: create modify
  Server/controllers/board/boardType/modify.js
Labels: Bare, C:3h, DB

#40 Feat: create-id
  Server/controllers/board/boardType/id.js
Labels: Bare, C:3h, DB

#41 Feature/37/create comment
  Server/config/config.js
  Server/controllers/board/boardType/comment.js
  Server/controllers/board/boardType/write.js
  Server/migrations/202009021224-user.js
  Server/migrations/202009021225-boardtype.js
  Server/migrations/202009021227-file.js
  Server/migrations/202009021228-comment.js
  Server/models/board.js
  Server/models/comment.js
Labels: Bare, C:3h, DB
